/**
 * Bundles each Vercel Function into ONE self-contained ESM file under api/.
 *
 * The functions share code with the game (scoring.ts, geo.ts, pick.ts and the
 * locations dataset). Bundling them avoids Node-ESM import-extension and JSON
 * import pitfalls on the serverless runtime: each api/*.js has zero local imports.
 *
 * Run: npm run build:api   (also runs automatically before `npm run build`)
 */
import { build } from 'esbuild';

await build({
  entryPoints: { session: 'server/entries/session.ts', scores: 'server/entries/scores.ts' },
  outdir: 'api',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  minify: false,
  legalComments: 'none',
  banner: {
    js: '// GENERATED by scripts/build-api.mjs from server/ – do not edit by hand.\nimport { createRequire as __cr } from "node:module"; const require = __cr(import.meta.url);',
  },
  logLevel: 'info',
});
